### ISSUE TITLE
uploading result files

### ISSUE THREAD

**Issue by ibaned** [UGAWG/adapt-benchmarks#1]
Should we commit adapted meshes in `.meshb` format to this repository as we start getting results from each of the tools ?
In other words, are there objections to committing files above a certain size to this repository ?
@UGAWG/all

**Comment by mikepark** [comment]
I'd like to keep the benchmarks repo as small as possible. That will encourage people outside of our group to use it. I think small items like statistics would be appropriate. What are the alternatives? A repo for only results, https://git-lfs.github.com/, etc?

**Comment by ibaned** [comment]
Yes. LFS or not, a separate repo for large files is usually what I end up doing. I assume this repository will be allowed to hold things like images (for the paper). I'll go ahead and create a separate repo for full results.

**Comment by ibaned** [comment]
Okay, I made [this repo](https://github.com/UGAWG/adapt-results). Each group is encouraged to create a subdirectory for their code. If you want we can require the use of LFS, I'm fine either way. Thats all I can do until I actually program `.meshb` output...
